


class DataList {


  static const Map<String, int> District1 = {
    "Select District":0,
    "Bagerhat":	28,
    "Bandarban":	11,
    "Barguna":	35,
    "Barisal":	33,
    "Bhola":	34,
    "Bogura":	14,
    "Brahmanbaria":	3,
    "Chandpur":	6,
    "Chapainawabganj":	18,
    "Chattogram":	8,
    "Chuadanga":	24,
    "Coxsbazar":	9,
    "Cumilla":	1,
    "Dhaka":47,
    "Dinajpur":54,
    "Faridpur":52,
    "Feni":2,
    "Gaibandha":57,
    "Gazipur":41,
    "Gopalganj":51,
    "Habiganj":38,
    "Jamalpur":63,
    "Jashore":20,
    "Jhalakathi":30,
    "Jhenaidah":29,
    "Joypurhat":17,
    "Khagrachhari":10,
    "Khulna":27,
    "Kishoreganj":45,
    "Kurigram":60,
    "Kushtia":25,
    "Lakshmipur":	7,
    "Lalmonirhat":	55,
    "Madaripur":	50,
    "Magura":	26,
    "Manikganj":	46,
    "Meherpur":	22,
    "Moulvibazar":	37,
    "Munshiganj":	48,
    "Mymensingh":	62,
    "Naogaon":	19,
    "Narail":	23,
    "Narayanganj":	43,
    "Narsingdi":	40,
    "Natore":	16,
    "Netrokona":	64,
    "Nilphamari":	56,
    "Noakhali":	5,
    "Pabna":	13,
    "Panchagarh":	53,
    "Patuakhali":	31,
    "Pirojpur":	32,
    "Rajbari":	49,
    "Rajshahi":	15,
    "Rangamati":	4,
    "Rangpur":	59,
    "Satkhira":	21,
    "Shariatpur":	42,
    "Sherpur":	61,
    "Sirajganj":	12,
    "Sunamganj":	39,
    "Sylhet":	36,
    "Tangail":	44,
    "Thakurgaon":	58,





  };


  List<List<String>> Thana1=[
    ["Select Thana"],
    ["Select Thana", "Barura", "Brahmanpara", "Burichong", "Cumilla Adarsha Sadar", "Cumilla Sadar South", "Chandina", "Chauddagram", "Daudkandi","Debidwar", "Homna", "Laksam", "Lalmai", "Monohorgonj", "Meghna", "Muradnagar", "Nangalkot", "Titas"],
    ["Select Thana","Chhagalnaiya","Daganbhuiyan","Feni Sadar","Fulgazi","Parshuram","Sonagazi"],
    ["Select Thana","Brahmanbaria Sadar","Ashuganj","Nasirnagar","Nabinagar","Sarail","Kasba","Akhaura","Bancharampur","Bijoynagar"],
    ["Select Thana","Barkal","Bagaichhari","Belaichhari","Juraichhari","Naniarchar","Kaptai","Kaukhali","Langadu","Rajasthali","Rangamati Sadar"],
    ["Select Thana","Senbagh", "Begumganj" , "Chatkhil" , "Companiganj" , "Noakhali Sadar" , "Hatiya", "Kabirhat" , "Sonaimuri" , "Suborno Char" , "Bhashan Char",],
    ["Select Thana","Chandpur Sadar","Faridganj","Haimchar","Haziganj","Kachua","Matlab Uttar","Matlab Dakshin","Shahrasti"],
    ["Select Thana","Kamalnagar","Lakshmipur Sadar","Raipur","Ramganj","Ramgati"],
    ["Select Thana","Anwara", "Banshkhali", "Boalkhali", "Chandanaish", "Fatikchhari", "Hathazari", "Karnaphuli", "Lohagara", "Mirsharai", "Patiya", "Rangunia", "Raozan", "Sandwip", "Satkania", "Sitakunda",],
    ["Select Thana","9"],
    ["Select Thana","10"],
    ["Select Thana","11"],
    ["Select Thana","12"],
    ["Select Thana","13"],
    ["Select Thana","14"],
    ["Select Thana","15"],
    ["Select Thana","16"],
    ["Select Thana","17"],
    ["Select Thana","18"],
    ["Select Thana","19"],
    ["Select Thana","20"],
    ["Select Thana","21"],
    ["Select Thana","22"],
    ["Select Thana","23"],
    ["Select Thana","24"],
    ["Select Thana","25"],
    ["Select Thana","26"],
    ["Select Thana","27"],
    ["Select Thana","28"],
    ["Select Thana","29"],
    ["Select Thana","30"],
    ["Select Thana","31"],
    ["Select Thana","32"],
    ["Select Thana","33"],
    ["Select Thana","34"],
    ["Select Thana","35"],
    ["Select Thana","36"],
    ["Select Thana","37"],
    ["Select Thana","38"],
    ["Select Thana","39"],
    ["Select Thana","40"],
    ["Select Thana","41"],
    ["Select Thana","42"],
    ["Select Thana","43"],
    ["Select Thana","44"],
    ["Select Thana","45"],
    ["Select Thana","46"],
    ["Select Thana","47"],
    ["Select Thana","48"],
    ["Select Thana","49"],
    ["Select Thana","50"],
    ["Select Thana","51"],
    ["Select Thana","52"],
    ["Select Thana","53"],
    ["Select Thana","54"],
    ["Select Thana","55"],
    ["Select Thana","56"],
    ["Select Thana","57"],
    ["Select Thana","58"],
    ["Select Thana","59"],
    ["Select Thana","60"],
    ["Select Thana","61"],
    ["Select Thana","62"],
    ["Select Thana","63"],
    ["Select Thana","64"],



  ];










}